// NFL kicking venues — generated by scripts/analysis/gillette-uprights/export_all.py
// Do not edit by hand; rerun the script to refresh.
//
// Every field goal 2002-2025 from nflverse play-by-play. Each venue is scored
// against a LEAVE-ONE-OUT baseline: the expected-make model (natural spline in
// kick distance + season fixed effects) is refit for each venue with that
// venue's own kicks held out, so no stadium is graded against itself. Blocked
// kicks are excluded (a block is a line-of-scrimmage failure, not an aiming
// one). Venues need 150+ visiting-kicker attempts to qualify.

export type StadiumBand = { diff: number; n: number };

export type StadiumBands = { u30: StadiumBand | null; d30: StadiumBand | null; d40: StadiumBand | null; d50: StadiumBand | null };

export type StadiumSeason = { season: number; n: number; diff: number };

export type Stadium = {
  id: string;
  name: string;
  teams: string[];
  roof: string;
  surface: string;
  firstSeason: number;
  lastSeason: number;
  games: number;
  /** visiting-kicker FG attempts */
  visN: number;
  visPct: number;
  visExp: number;
  /** actual minus expected, percentage points */
  visDiff: number;
  visZ: number;
  visRank: number;
  homeN: number;
  homePct: number;
  homeDiff: number;
  /** home minus visitor, both distance-adjusted */
  gap: number;
  gapZ: number;
  gapRank: number;
  bands: StadiumBands;
  windyDiff: number | null;
  windyN: number;
  /** gross punt distance vs expectation, yards */
  puntOE: number | null;
  puntN: number;
  koDistOE: number | null;
  touchback: number | null;
  /** share of 4th-down 50+ yd chances the home team kicked */
  homeLongKickRate: number | null;
  homeLongKickN: number;
  wideOnly: number | null;
  missN: number;
  /** Q2+Q4 minus Q1+Q3 for visiting kickers — a direction-of-play proxy */
  dirSplit: number | null;
  bySeason: StadiumSeason[];
};

export const stadiumMeta = {
  "venues": 36,
  "seasons": "2002-2025",
  "totalFG": 24307,
  "totalPunts": 57439,
  "leagueHome": 85.7,
  "leagueVisitor": 84.6,
  "leagueLongKickRate": 18.4,
  "meanGap": 0.8,
  "sdGap": 2.9,
  "gapChi2P": 0.202,
  "visChi2P": 0.006
} as const;

export const stadiums: Stadium[] = [
  {
    "id": "BOS00",
    "name": "Gillette Stadium",
    "teams": [
      "NE"
    ],
    "roof": "outdoors",
    "surface": "fieldturf",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 211,
    "visN": 363,
    "visPct": 79.3,
    "visExp": 85.8,
    "visDiff": -6.5,
    "visZ": -3.75,
    "homeN": 431,
    "homePct": 87.0,
    "homeDiff": -1.1,
    "gap": 5.4,
    "gapZ": 2.37,
    "bands": {
      "u30": {
        "diff": 1.1,
        "n": 98
      },
      "d30": {
        "diff": -8.1,
        "n": 102
      },
      "d40": {
        "diff": -11.5,
        "n": 120
      },
      "d50": {
        "diff": -5.9,
        "n": 43
      }
    },
    "windyDiff": -13.7,
    "windyN": 39,
    "puntOE": -0.9,
    "puntN": 1858,
    "koDistOE": -0.51,
    "touchback": 51.4,
    "homeLongKickRate": 6.9,
    "homeLongKickN": 116,
    "wideOnly": 72.0,
    "missN": 75,
    "dirSplit": -6.6,
    "bySeason": [
      {
        "season": 2002,
        "n": 14,
        "diff": -22.4
      },
      {
        "season": 2003,
        "n": 19,
        "diff": -13.4
      },
      {
        "season": 2004,
        "n": 10,
        "diff": -8.2
      },
      {
        "season": 2005,
        "n": 18,
        "diff": -6.4
      },
      {
        "season": 2006,
        "n": 18,
        "diff": -0.7
      },
      {
        "season": 2007,
        "n": 11,
        "diff": 0.9
      },
      {
        "season": 2008,
        "n": 13,
        "diff": 0.2
      },
      {
        "season": 2009,
        "n": 7,
        "diff": 4.4
      },
      {
        "season": 2010,
        "n": 14,
        "diff": -12.8
      },
      {
        "season": 2011,
        "n": 12,
        "diff": -6.3
      },
      {
        "season": 2012,
        "n": 15,
        "diff": -2.0
      },
      {
        "season": 2013,
        "n": 16,
        "diff": -6.2
      },
      {
        "season": 2014,
        "n": 19,
        "diff": -3.7
      },
      {
        "season": 2015,
        "n": 16,
        "diff": -8.2
      },
      {
        "season": 2016,
        "n": 20,
        "diff": 0.0
      },
      {
        "season": 2017,
        "n": 17,
        "diff": -4.7
      },
      {
        "season": 2018,
        "n": 15,
        "diff": -6.4
      },
      {
        "season": 2019,
        "n": 13,
        "diff": 5.5
      },
      {
        "season": 2020,
        "n": 16,
        "diff": 0.4
      },
      {
        "season": 2021,
        "n": 17,
        "diff": -21.9
      },
      {
        "season": 2022,
        "n": 12,
        "diff": -10.9
      },
      {
        "season": 2023,
        "n": 21,
        "diff": -4.8
      },
      {
        "season": 2024,
        "n": 19,
        "diff": -10.2
      },
      {
        "season": 2025,
        "n": 11,
        "diff": -12.6
      }
    ],
    "visRank": 1,
    "gapRank": 3
  },
  {
    "id": "CHI98",
    "name": "Soldier Field",
    "teams": [
      "CHI"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2003,
    "lastSeason": 2025,
    "games": 192,
    "visN": 355,
    "visPct": 82.5,
    "visExp": 86.6,
    "visDiff": -4.1,
    "visZ": -2.44,
    "homeN": 336,
    "homePct": 85.4,
    "homeDiff": -0.9,
    "gap": 3.2,
    "gapZ": 1.3,
    "bands": {
      "u30": {
        "diff": -1.0,
        "n": 100
      },
      "d30": {
        "diff": -3.5,
        "n": 120
      },
      "d40": {
        "diff": -11.1,
        "n": 83
      },
      "d50": {
        "diff": -0.5,
        "n": 52
      }
    },
    "windyDiff": -7.3,
    "windyN": 67,
    "puntOE": -1.53,
    "puntN": 1816,
    "koDistOE": -0.7,
    "touchback": 43.5,
    "homeLongKickRate": 11.9,
    "homeLongKickN": 134,
    "wideOnly": 65.6,
    "missN": 61,
    "dirSplit": -2.6,
    "bySeason": [
      {
        "season": 2003,
        "n": 14,
        "diff": 1.5
      },
      {
        "season": 2004,
        "n": 19,
        "diff": -7.1
      },
      {
        "season": 2005,
        "n": 16,
        "diff": -10.6
      },
      {
        "season": 2006,
        "n": 13,
        "diff": -11.1
      },
      {
        "season": 2007,
        "n": 12,
        "diff": 10.7
      },
      {
        "season": 2008,
        "n": 14,
        "diff": -13.9
      },
      {
        "season": 2009,
        "n": 13,
        "diff": -5.9
      },
      {
        "season": 2010,
        "n": 16,
        "diff": -1.7
      },
      {
        "season": 2011,
        "n": 17,
        "diff": -4.5
      },
      {
        "season": 2012,
        "n": 14,
        "diff": -7.5
      },
      {
        "season": 2013,
        "n": 12,
        "diff": 1.2
      },
      {
        "season": 2014,
        "n": 18,
        "diff": -4.8
      },
      {
        "season": 2015,
        "n": 10,
        "diff": 7.8
      },
      {
        "season": 2016,
        "n": 16,
        "diff": 6.5
      },
      {
        "season": 2017,
        "n": 19,
        "diff": 4.6
      },
      {
        "season": 2018,
        "n": 14,
        "diff": 9.1
      },
      {
        "season": 2019,
        "n": 15,
        "diff": -22.4
      },
      {
        "season": 2020,
        "n": 18,
        "diff": -0.6
      },
      {
        "season": 2021,
        "n": 14,
        "diff": 5.3
      },
      {
        "season": 2022,
        "n": 16,
        "diff": -18.5
      },
      {
        "season": 2023,
        "n": 15,
        "diff": -13.3
      },
      {
        "season": 2024,
        "n": 20,
        "diff": -2.7
      },
      {
        "season": 2025,
        "n": 20,
        "diff": -9.1
      }
    ],
    "visRank": 2,
    "gapRank": 9
  },
  {
    "id": "CLE00",
    "name": "Cleveland Browns Stadium",
    "teams": [
      "CLE"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 191,
    "visN": 356,
    "visPct": 81.2,
    "visExp": 85.1,
    "visDiff": -3.9,
    "visZ": -2.21,
    "homeN": 310,
    "homePct": 84.2,
    "homeDiff": -3.3,
    "gap": 0.6,
    "gapZ": 0.24,
    "bands": {
      "u30": {
        "diff": -3.1,
        "n": 93
      },
      "d30": {
        "diff": 0.4,
        "n": 87
      },
      "d40": {
        "diff": -5.8,
        "n": 134
      },
      "d50": {
        "diff": -8.9,
        "n": 42
      }
    },
    "windyDiff": -7.6,
    "windyN": 108,
    "puntOE": -0.77,
    "puntN": 1883,
    "koDistOE": -0.2,
    "touchback": 50.1,
    "homeLongKickRate": 11.3,
    "homeLongKickN": 150,
    "wideOnly": 86.6,
    "missN": 67,
    "dirSplit": -1.9,
    "bySeason": [
      {
        "season": 2002,
        "n": 19,
        "diff": -0.5
      },
      {
        "season": 2003,
        "n": 19,
        "diff": -1.0
      },
      {
        "season": 2004,
        "n": 10,
        "diff": -4.6
      },
      {
        "season": 2005,
        "n": 15,
        "diff": -2.2
      },
      {
        "season": 2006,
        "n": 17,
        "diff": 3.4
      },
      {
        "season": 2007,
        "n": 13,
        "diff": -10.8
      },
      {
        "season": 2008,
        "n": 14,
        "diff": -14.8
      },
      {
        "season": 2009,
        "n": 17,
        "diff": 2.7
      },
      {
        "season": 2010,
        "n": 21,
        "diff": -11.6
      },
      {
        "season": 2011,
        "n": 17,
        "diff": -12.7
      },
      {
        "season": 2012,
        "n": 9,
        "diff": -7.7
      },
      {
        "season": 2013,
        "n": 14,
        "diff": 14.5
      },
      {
        "season": 2014,
        "n": 18,
        "diff": 3.8
      },
      {
        "season": 2015,
        "n": 18,
        "diff": -0.7
      },
      {
        "season": 2016,
        "n": 13,
        "diff": -9.3
      },
      {
        "season": 2017,
        "n": 12,
        "diff": 0.9
      },
      {
        "season": 2018,
        "n": 11,
        "diff": 2.9
      },
      {
        "season": 2019,
        "n": 16,
        "diff": -7.0
      },
      {
        "season": 2020,
        "n": 16,
        "diff": -0.8
      },
      {
        "season": 2021,
        "n": 14,
        "diff": 14.3
      },
      {
        "season": 2022,
        "n": 13,
        "diff": -18.7
      },
      {
        "season": 2023,
        "n": 10,
        "diff": -15.7
      },
      {
        "season": 2024,
        "n": 15,
        "diff": -19.7
      },
      {
        "season": 2025,
        "n": 15,
        "diff": -5.0
      }
    ],
    "visRank": 3,
    "gapRank": 18
  },
  {
    "id": "OAK00",
    "name": "Oakland-Alameda County Stadium",
    "teams": [
      "LV"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2019,
    "games": 139,
    "visN": 278,
    "visPct": 81.3,
    "visExp": 85.0,
    "visDiff": -3.7,
    "visZ": -1.83,
    "homeN": 274,
    "homePct": 80.7,
    "homeDiff": -0.8,
    "gap": 2.9,
    "gapZ": 0.98,
    "bands": {
      "u30": {
        "diff": 0.1,
        "n": 88
      },
      "d30": {
        "diff": -6.5,
        "n": 76
      },
      "d40": {
        "diff": -2.4,
        "n": 83
      },
      "d50": {
        "diff": -10.6,
        "n": 31
      }
    },
    "windyDiff": -3.8,
    "windyN": 46,
    "puntOE": 0.92,
    "puntN": 1288,
    "koDistOE": -0.27,
    "touchback": 48.9,
    "homeLongKickRate": 25.0,
    "homeLongKickN": 80,
    "wideOnly": 78.4,
    "missN": 51,
    "dirSplit": 3.1,
    "bySeason": [
      {
        "season": 2002,
        "n": 16,
        "diff": -15.0
      },
      {
        "season": 2003,
        "n": 15,
        "diff": -9.1
      },
      {
        "season": 2004,
        "n": 13,
        "diff": -11.5
      },
      {
        "season": 2005,
        "n": 19,
        "diff": 7.2
      },
      {
        "season": 2006,
        "n": 20,
        "diff": -3.6
      },
      {
        "season": 2007,
        "n": 17,
        "diff": 0.8
      },
      {
        "season": 2008,
        "n": 16,
        "diff": 0.0
      },
      {
        "season": 2009,
        "n": 21,
        "diff": -11.1
      },
      {
        "season": 2010,
        "n": 20,
        "diff": -10.5
      },
      {
        "season": 2011,
        "n": 9,
        "diff": 1.5
      },
      {
        "season": 2012,
        "n": 17,
        "diff": 7.6
      },
      {
        "season": 2013,
        "n": 11,
        "diff": -10.5
      },
      {
        "season": 2014,
        "n": 13,
        "diff": 4.2
      },
      {
        "season": 2015,
        "n": 21,
        "diff": -0.2
      },
      {
        "season": 2016,
        "n": 10,
        "diff": 1.4
      },
      {
        "season": 2017,
        "n": 13,
        "diff": 6.8
      },
      {
        "season": 2018,
        "n": 16,
        "diff": -12.9
      },
      {
        "season": 2019,
        "n": 11,
        "diff": -9.1
      }
    ],
    "visRank": 4,
    "gapRank": 11
  },
  {
    "id": "GNB00",
    "name": "Lambeau Field",
    "teams": [
      "GB"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 202,
    "visN": 343,
    "visPct": 82.2,
    "visExp": 85.2,
    "visDiff": -2.9,
    "visZ": -1.65,
    "homeN": 384,
    "homePct": 82.8,
    "homeDiff": -3.0,
    "gap": -0.1,
    "gapZ": -0.03,
    "bands": {
      "u30": {
        "diff": -0.3,
        "n": 85
      },
      "d30": {
        "diff": 0.0,
        "n": 108
      },
      "d40": {
        "diff": -6.8,
        "n": 100
      },
      "d50": {
        "diff": -6.0,
        "n": 50
      }
    },
    "windyDiff": -10.1,
    "windyN": 46,
    "puntOE": -1.08,
    "puntN": 1717,
    "koDistOE": -0.86,
    "touchback": 42.3,
    "homeLongKickRate": 10.7,
    "homeLongKickN": 131,
    "wideOnly": 78.0,
    "missN": 59,
    "dirSplit": -3.2,
    "bySeason": [
      {
        "season": 2002,
        "n": 18,
        "diff": -19.2
      },
      {
        "season": 2003,
        "n": 17,
        "diff": -0.5
      },
      {
        "season": 2004,
        "n": 14,
        "diff": -20.2
      },
      {
        "season": 2005,
        "n": 16,
        "diff": -9.4
      },
      {
        "season": 2006,
        "n": 13,
        "diff": 13.0
      },
      {
        "season": 2007,
        "n": 16,
        "diff": -3.2
      },
      {
        "season": 2008,
        "n": 11,
        "diff": 2.4
      },
      {
        "season": 2009,
        "n": 7,
        "diff": 4.0
      },
      {
        "season": 2010,
        "n": 14,
        "diff": 13.2
      },
      {
        "season": 2011,
        "n": 16,
        "diff": -14.3
      },
      {
        "season": 2012,
        "n": 16,
        "diff": -3.2
      },
      {
        "season": 2013,
        "n": 18,
        "diff": -5.8
      },
      {
        "season": 2014,
        "n": 7,
        "diff": 0.2
      },
      {
        "season": 2015,
        "n": 11,
        "diff": 2.7
      },
      {
        "season": 2016,
        "n": 16,
        "diff": 4.1
      },
      {
        "season": 2017,
        "n": 20,
        "diff": -3.4
      },
      {
        "season": 2018,
        "n": 17,
        "diff": -7.7
      },
      {
        "season": 2019,
        "n": 15,
        "diff": 6.5
      },
      {
        "season": 2020,
        "n": 11,
        "diff": 5.2
      },
      {
        "season": 2021,
        "n": 12,
        "diff": 14.3
      },
      {
        "season": 2022,
        "n": 13,
        "diff": -18.8
      },
      {
        "season": 2023,
        "n": 17,
        "diff": -7.7
      },
      {
        "season": 2024,
        "n": 12,
        "diff": 3.4
      },
      {
        "season": 2025,
        "n": 16,
        "diff": -5.4
      }
    ],
    "visRank": 5,
    "gapRank": 20
  },
  {
    "id": "SFO01",
    "name": "Levi's\u00ae Stadium",
    "teams": [
      "SF"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2014,
    "lastSeason": 2025,
    "games": 101,
    "visN": 173,
    "visPct": 83.8,
    "visExp": 86.7,
    "visDiff": -2.9,
    "visZ": -1.19,
    "homeN": 195,
    "homePct": 92.3,
    "homeDiff": 5.0,
    "gap": 7.9,
    "gapZ": 2.39,
    "bands": {
      "u30": {
        "diff": -0.7,
        "n": 42
      },
      "d30": {
        "diff": -0.5,
        "n": 50
      },
      "d40": {
        "diff": -6.3,
        "n": 54
      },
      "d50": {
        "diff": -4.2,
        "n": 27
      }
    },
    "windyDiff": null,
    "windyN": 13,
    "puntOE": 0.16,
    "puntN": 851,
    "koDistOE": -0.53,
    "touchback": 51.5,
    "homeLongKickRate": 23.9,
    "homeLongKickN": 71,
    "wideOnly": 75.0,
    "missN": 28,
    "dirSplit": 8.3,
    "bySeason": [
      {
        "season": 2014,
        "n": 11,
        "diff": 11.1
      },
      {
        "season": 2015,
        "n": 21,
        "diff": -12.1
      },
      {
        "season": 2016,
        "n": 17,
        "diff": -5.7
      },
      {
        "season": 2017,
        "n": 17,
        "diff": -5.5
      },
      {
        "season": 2018,
        "n": 11,
        "diff": -7.8
      },
      {
        "season": 2019,
        "n": 12,
        "diff": 11.1
      },
      {
        "season": 2020,
        "n": 12,
        "diff": 1.0
      },
      {
        "season": 2021,
        "n": 9,
        "diff": 3.9
      },
      {
        "season": 2022,
        "n": 13,
        "diff": -10.3
      },
      {
        "season": 2023,
        "n": 15,
        "diff": -0.8
      },
      {
        "season": 2024,
        "n": 14,
        "diff": 19.6
      },
      {
        "season": 2025,
        "n": 21,
        "diff": -19.1
      }
    ],
    "visRank": 5,
    "gapRank": 1
  },
  {
    "id": "WAS00",
    "name": "Commanders Field",
    "teams": [
      "WAS"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 197,
    "visN": 371,
    "visPct": 83.0,
    "visExp": 85.5,
    "visDiff": -2.5,
    "visZ": -1.44,
    "homeN": 368,
    "homePct": 81.0,
    "homeDiff": -4.8,
    "gap": -2.3,
    "gapZ": -0.97,
    "bands": {
      "u30": {
        "diff": -0.3,
        "n": 90
      },
      "d30": {
        "diff": -4.3,
        "n": 127
      },
      "d40": {
        "diff": -1.3,
        "n": 107
      },
      "d50": {
        "diff": -4.3,
        "n": 47
      }
    },
    "windyDiff": null,
    "windyN": 14,
    "puntOE": -0.55,
    "puntN": 1792,
    "koDistOE": -0.28,
    "touchback": 54.7,
    "homeLongKickRate": 9.0,
    "homeLongKickN": 144,
    "wideOnly": 66.1,
    "missN": 62,
    "dirSplit": 0.3,
    "bySeason": [
      {
        "season": 2002,
        "n": 15,
        "diff": 5.2
      },
      {
        "season": 2003,
        "n": 16,
        "diff": -18.1
      },
      {
        "season": 2004,
        "n": 8,
        "diff": 6.8
      },
      {
        "season": 2005,
        "n": 15,
        "diff": -17.0
      },
      {
        "season": 2006,
        "n": 16,
        "diff": 11.6
      },
      {
        "season": 2007,
        "n": 17,
        "diff": -4.9
      },
      {
        "season": 2008,
        "n": 13,
        "diff": 7.8
      },
      {
        "season": 2009,
        "n": 18,
        "diff": 1.8
      },
      {
        "season": 2010,
        "n": 19,
        "diff": -12.7
      },
      {
        "season": 2011,
        "n": 16,
        "diff": 0.6
      },
      {
        "season": 2012,
        "n": 16,
        "diff": 5.9
      },
      {
        "season": 2013,
        "n": 13,
        "diff": -5.3
      },
      {
        "season": 2014,
        "n": 16,
        "diff": -17.2
      },
      {
        "season": 2015,
        "n": 13,
        "diff": 2.3
      },
      {
        "season": 2016,
        "n": 16,
        "diff": -2.7
      },
      {
        "season": 2017,
        "n": 19,
        "diff": 2.9
      },
      {
        "season": 2018,
        "n": 13,
        "diff": -9.7
      },
      {
        "season": 2019,
        "n": 16,
        "diff": -18.8
      },
      {
        "season": 2020,
        "n": 17,
        "diff": -1.9
      },
      {
        "season": 2021,
        "n": 16,
        "diff": 12.1
      },
      {
        "season": 2022,
        "n": 13,
        "diff": -1.7
      },
      {
        "season": 2023,
        "n": 17,
        "diff": 6.1
      },
      {
        "season": 2024,
        "n": 14,
        "diff": -4.5
      },
      {
        "season": 2025,
        "n": 19,
        "diff": -2.9
      }
    ],
    "visRank": 7,
    "gapRank": 32
  },
  {
    "id": "NYC00",
    "name": "Giants Stadium",
    "teams": [
      "NYG",
      "NYJ"
    ],
    "roof": "outdoors",
    "surface": "fieldturf",
    "firstSeason": 2002,
    "lastSeason": 2009,
    "games": 130,
    "visN": 230,
    "visPct": 81.7,
    "visExp": 84.1,
    "visDiff": -2.3,
    "visZ": -1.03,
    "homeN": 251,
    "homePct": 84.5,
    "homeDiff": -1.7,
    "gap": 0.6,
    "gapZ": 0.2,
    "bands": {
      "u30": {
        "diff": -1.4,
        "n": 74
      },
      "d30": {
        "diff": 1.1,
        "n": 67
      },
      "d40": {
        "diff": -1.6,
        "n": 75
      },
      "d50": {
        "diff": -27.4,
        "n": 14
      }
    },
    "windyDiff": -8.2,
    "windyN": 43,
    "puntOE": -1.83,
    "puntN": 1178,
    "koDistOE": null,
    "touchback": null,
    "homeLongKickRate": 8.5,
    "homeLongKickN": 82,
    "wideOnly": 82.9,
    "missN": 41,
    "dirSplit": 0.3,
    "bySeason": [
      {
        "season": 2002,
        "n": 30,
        "diff": -4.5
      },
      {
        "season": 2003,
        "n": 33,
        "diff": -5.7
      },
      {
        "season": 2004,
        "n": 21,
        "diff": 1.0
      },
      {
        "season": 2005,
        "n": 34,
        "diff": -3.3
      },
      {
        "season": 2006,
        "n": 29,
        "diff": -5.3
      },
      {
        "season": 2007,
        "n": 34,
        "diff": 3.0
      },
      {
        "season": 2008,
        "n": 24,
        "diff": 5.4
      },
      {
        "season": 2009,
        "n": 25,
        "diff": -8.0
      }
    ],
    "visRank": 8,
    "gapRank": 18
  },
  {
    "id": "TAM00",
    "name": "Raymond James Stadium",
    "teams": [
      "TB"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 198,
    "visN": 366,
    "visPct": 83.6,
    "visExp": 85.6,
    "visDiff": -2.0,
    "visZ": -1.15,
    "homeN": 357,
    "homePct": 81.0,
    "homeDiff": -3.1,
    "gap": -1.1,
    "gapZ": -0.44,
    "bands": {
      "u30": {
        "diff": 0.1,
        "n": 101
      },
      "d30": {
        "diff": -2.1,
        "n": 103
      },
      "d40": {
        "diff": -1.7,
        "n": 115
      },
      "d50": {
        "diff": -6.9,
        "n": 47
      }
    },
    "windyDiff": null,
    "windyN": 20,
    "puntOE": 0.05,
    "puntN": 1776,
    "koDistOE": 0.26,
    "touchback": 64.4,
    "homeLongKickRate": 19.7,
    "homeLongKickN": 122,
    "wideOnly": 81.0,
    "missN": 58,
    "dirSplit": -5.5,
    "bySeason": [
      {
        "season": 2002,
        "n": 10,
        "diff": 8.6
      },
      {
        "season": 2003,
        "n": 16,
        "diff": 1.9
      },
      {
        "season": 2004,
        "n": 9,
        "diff": 1.3
      },
      {
        "season": 2005,
        "n": 15,
        "diff": 15.1
      },
      {
        "season": 2006,
        "n": 15,
        "diff": 18.2
      },
      {
        "season": 2007,
        "n": 12,
        "diff": -8.7
      },
      {
        "season": 2008,
        "n": 15,
        "diff": 3.7
      },
      {
        "season": 2009,
        "n": 12,
        "diff": 1.7
      },
      {
        "season": 2010,
        "n": 11,
        "diff": -1.0
      },
      {
        "season": 2011,
        "n": 12,
        "diff": -8.2
      },
      {
        "season": 2012,
        "n": 13,
        "diff": -39.9
      },
      {
        "season": 2013,
        "n": 18,
        "diff": 5.8
      },
      {
        "season": 2014,
        "n": 19,
        "diff": -0.2
      },
      {
        "season": 2015,
        "n": 20,
        "diff": 6.9
      },
      {
        "season": 2016,
        "n": 18,
        "diff": -9.2
      },
      {
        "season": 2017,
        "n": 11,
        "diff": 7.5
      },
      {
        "season": 2018,
        "n": 12,
        "diff": -4.7
      },
      {
        "season": 2019,
        "n": 20,
        "diff": 6.4
      },
      {
        "season": 2020,
        "n": 18,
        "diff": -14.4
      },
      {
        "season": 2021,
        "n": 19,
        "diff": -6.4
      },
      {
        "season": 2022,
        "n": 13,
        "diff": -0.1
      },
      {
        "season": 2023,
        "n": 19,
        "diff": -3.9
      },
      {
        "season": 2024,
        "n": 26,
        "diff": -13.3
      },
      {
        "season": 2025,
        "n": 13,
        "diff": -9.1
      }
    ],
    "visRank": 9,
    "gapRank": 24
  },
  {
    "id": "SEA00",
    "name": "Lumen Field",
    "teams": [
      "SEA"
    ],
    "roof": "outdoors",
    "surface": "fieldturf",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 205,
    "visN": 394,
    "visPct": 83.0,
    "visExp": 84.9,
    "visDiff": -1.9,
    "visZ": -1.14,
    "homeN": 397,
    "homePct": 88.2,
    "homeDiff": 2.0,
    "gap": 3.9,
    "gapZ": 1.67,
    "bands": {
      "u30": {
        "diff": 0.1,
        "n": 93
      },
      "d30": {
        "diff": -2.3,
        "n": 126
      },
      "d40": {
        "diff": 0.7,
        "n": 117
      },
      "d50": {
        "diff": -9.8,
        "n": 58
      }
    },
    "windyDiff": -4.2,
    "windyN": 32,
    "puntOE": -0.36,
    "puntN": 1911,
    "koDistOE": -0.01,
    "touchback": 47.7,
    "homeLongKickRate": 13.6,
    "homeLongKickN": 140,
    "wideOnly": 75.8,
    "missN": 66,
    "dirSplit": -5.2,
    "bySeason": [
      {
        "season": 2002,
        "n": 12,
        "diff": -5.2
      },
      {
        "season": 2003,
        "n": 16,
        "diff": -1.0
      },
      {
        "season": 2004,
        "n": 16,
        "diff": -5.5
      },
      {
        "season": 2005,
        "n": 22,
        "diff": -7.8
      },
      {
        "season": 2006,
        "n": 15,
        "diff": 3.9
      },
      {
        "season": 2007,
        "n": 12,
        "diff": -8.3
      },
      {
        "season": 2008,
        "n": 24,
        "diff": 4.5
      },
      {
        "season": 2009,
        "n": 15,
        "diff": -13.2
      },
      {
        "season": 2010,
        "n": 13,
        "diff": 2.8
      },
      {
        "season": 2011,
        "n": 19,
        "diff": -4.9
      },
      {
        "season": 2012,
        "n": 12,
        "diff": 6.0
      },
      {
        "season": 2013,
        "n": 14,
        "diff": -5.2
      },
      {
        "season": 2014,
        "n": 18,
        "diff": 3.8
      },
      {
        "season": 2015,
        "n": 12,
        "diff": 9.0
      },
      {
        "season": 2016,
        "n": 12,
        "diff": -5.8
      },
      {
        "season": 2017,
        "n": 15,
        "diff": 11.9
      },
      {
        "season": 2018,
        "n": 14,
        "diff": 2.7
      },
      {
        "season": 2019,
        "n": 18,
        "diff": -1.3
      },
      {
        "season": 2020,
        "n": 17,
        "diff": -7.0
      },
      {
        "season": 2021,
        "n": 15,
        "diff": -15.1
      },
      {
        "season": 2022,
        "n": 22,
        "diff": -3.7
      },
      {
        "season": 2023,
        "n": 18,
        "diff": -3.3
      },
      {
        "season": 2024,
        "n": 22,
        "diff": -0.0
      },
      {
        "season": 2025,
        "n": 21,
        "diff": -2.3
      }
    ],
    "visRank": 10,
    "gapRank": 5
  },
  {
    "id": "SFO00",
    "name": "Candlestick Park",
    "teams": [
      "SF"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2013,
    "games": 98,
    "visN": 171,
    "visPct": 83.0,
    "visExp": 85.0,
    "visDiff": -1.9,
    "visZ": -0.75,
    "homeN": 196,
    "homePct": 87.8,
    "homeDiff": 2.1,
    "gap": 4.1,
    "gapZ": 1.17,
    "bands": {
      "u30": {
        "diff": -4.2,
        "n": 48
      },
      "d30": {
        "diff": 2.6,
        "n": 54
      },
      "d40": {
        "diff": -2.1,
        "n": 54
      },
      "d50": {
        "diff": -10.3,
        "n": 15
      }
    },
    "windyDiff": -7.6,
    "windyN": 40,
    "puntOE": 0.21,
    "puntN": 978,
    "koDistOE": -0.02,
    "touchback": 41.3,
    "homeLongKickRate": 16.4,
    "homeLongKickN": 55,
    "wideOnly": 86.2,
    "missN": 29,
    "dirSplit": 2.9,
    "bySeason": [
      {
        "season": 2002,
        "n": 14,
        "diff": -1.4
      },
      {
        "season": 2003,
        "n": 6,
        "diff": -26.1
      },
      {
        "season": 2004,
        "n": 13,
        "diff": -4.9
      },
      {
        "season": 2005,
        "n": 15,
        "diff": -4.0
      },
      {
        "season": 2006,
        "n": 17,
        "diff": 1.6
      },
      {
        "season": 2007,
        "n": 16,
        "diff": 12.8
      },
      {
        "season": 2008,
        "n": 20,
        "diff": 3.9
      },
      {
        "season": 2009,
        "n": 13,
        "diff": -6.4
      },
      {
        "season": 2010,
        "n": 13,
        "diff": -6.4
      },
      {
        "season": 2011,
        "n": 13,
        "diff": -1.4
      },
      {
        "season": 2012,
        "n": 20,
        "diff": -1.3
      },
      {
        "season": 2013,
        "n": 11,
        "diff": -11.6
      }
    ],
    "visRank": 10,
    "gapRank": 4
  },
  {
    "id": "PIT00",
    "name": "Acrisure Stadium",
    "teams": [
      "PIT"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 206,
    "visN": 338,
    "visPct": 83.7,
    "visExp": 85.2,
    "visDiff": -1.5,
    "visZ": -0.81,
    "homeN": 423,
    "homePct": 86.8,
    "homeDiff": 0.9,
    "gap": 2.4,
    "gapZ": 0.98,
    "bands": {
      "u30": {
        "diff": 2.2,
        "n": 83
      },
      "d30": {
        "diff": -0.4,
        "n": 93
      },
      "d40": {
        "diff": -1.4,
        "n": 122
      },
      "d50": {
        "diff": -11.7,
        "n": 40
      }
    },
    "windyDiff": null,
    "windyN": 24,
    "puntOE": -1.15,
    "puntN": 1883,
    "koDistOE": -0.53,
    "touchback": 46.4,
    "homeLongKickRate": 17.9,
    "homeLongKickN": 134,
    "wideOnly": 75.9,
    "missN": 54,
    "dirSplit": -1.0,
    "bySeason": [
      {
        "season": 2002,
        "n": 15,
        "diff": 2.3
      },
      {
        "season": 2003,
        "n": 8,
        "diff": -2.9
      },
      {
        "season": 2004,
        "n": 17,
        "diff": 1.9
      },
      {
        "season": 2005,
        "n": 13,
        "diff": -1.6
      },
      {
        "season": 2006,
        "n": 7,
        "diff": -22.0
      },
      {
        "season": 2007,
        "n": 10,
        "diff": -14.6
      },
      {
        "season": 2008,
        "n": 15,
        "diff": -3.8
      },
      {
        "season": 2009,
        "n": 13,
        "diff": -6.3
      },
      {
        "season": 2010,
        "n": 15,
        "diff": 0.5
      },
      {
        "season": 2011,
        "n": 12,
        "diff": -16.9
      },
      {
        "season": 2012,
        "n": 16,
        "diff": -7.8
      },
      {
        "season": 2013,
        "n": 14,
        "diff": 1.7
      },
      {
        "season": 2014,
        "n": 19,
        "diff": 6.4
      },
      {
        "season": 2015,
        "n": 12,
        "diff": 6.3
      },
      {
        "season": 2016,
        "n": 17,
        "diff": 2.7
      },
      {
        "season": 2017,
        "n": 9,
        "diff": 11.7
      },
      {
        "season": 2018,
        "n": 13,
        "diff": -0.2
      },
      {
        "season": 2019,
        "n": 13,
        "diff": -6.2
      },
      {
        "season": 2020,
        "n": 11,
        "diff": 0.3
      },
      {
        "season": 2021,
        "n": 18,
        "diff": 2.0
      },
      {
        "season": 2022,
        "n": 15,
        "diff": 5.2
      },
      {
        "season": 2023,
        "n": 18,
        "diff": 7.0
      },
      {
        "season": 2024,
        "n": 17,
        "diff": -10.3
      },
      {
        "season": 2025,
        "n": 21,
        "diff": -5.8
      }
    ],
    "visRank": 12,
    "gapRank": 13
  },
  {
    "id": "MIA00",
    "name": "Hard Rock Stadium",
    "teams": [
      "MIA"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 193,
    "visN": 387,
    "visPct": 83.5,
    "visExp": 84.6,
    "visDiff": -1.1,
    "visZ": -0.67,
    "homeN": 364,
    "homePct": 84.1,
    "homeDiff": -0.4,
    "gap": 0.8,
    "gapZ": 0.31,
    "bands": {
      "u30": {
        "diff": 2.0,
        "n": 100
      },
      "d30": {
        "diff": 1.7,
        "n": 110
      },
      "d40": {
        "diff": -8.8,
        "n": 113
      },
      "d50": {
        "diff": 2.5,
        "n": 64
      }
    },
    "windyDiff": -1.1,
    "windyN": 94,
    "puntOE": 1.12,
    "puntN": 1817,
    "koDistOE": 0.39,
    "touchback": 60.8,
    "homeLongKickRate": 17.2,
    "homeLongKickN": 122,
    "wideOnly": 87.5,
    "missN": 64,
    "dirSplit": 0.7,
    "bySeason": [
      {
        "season": 2002,
        "n": 10,
        "diff": 13.5
      },
      {
        "season": 2003,
        "n": 21,
        "diff": 8.6
      },
      {
        "season": 2004,
        "n": 10,
        "diff": -27.3
      },
      {
        "season": 2005,
        "n": 12,
        "diff": 18.2
      },
      {
        "season": 2006,
        "n": 18,
        "diff": -3.0
      },
      {
        "season": 2007,
        "n": 13,
        "diff": 3.2
      },
      {
        "season": 2008,
        "n": 19,
        "diff": -1.5
      },
      {
        "season": 2009,
        "n": 20,
        "diff": 15.1
      },
      {
        "season": 2010,
        "n": 16,
        "diff": 6.9
      },
      {
        "season": 2011,
        "n": 17,
        "diff": -13.0
      },
      {
        "season": 2012,
        "n": 19,
        "diff": -4.9
      },
      {
        "season": 2013,
        "n": 24,
        "diff": -1.5
      },
      {
        "season": 2014,
        "n": 14,
        "diff": -3.3
      },
      {
        "season": 2015,
        "n": 12,
        "diff": -18.4
      },
      {
        "season": 2016,
        "n": 17,
        "diff": -15.5
      },
      {
        "season": 2017,
        "n": 13,
        "diff": 4.6
      },
      {
        "season": 2018,
        "n": 19,
        "diff": -7.1
      },
      {
        "season": 2019,
        "n": 23,
        "diff": 3.1
      },
      {
        "season": 2020,
        "n": 11,
        "diff": -7.1
      },
      {
        "season": 2021,
        "n": 18,
        "diff": -3.2
      },
      {
        "season": 2022,
        "n": 12,
        "diff": 0.3
      },
      {
        "season": 2023,
        "n": 14,
        "diff": -2.7
      },
      {
        "season": 2024,
        "n": 19,
        "diff": -1.2
      },
      {
        "season": 2025,
        "n": 16,
        "diff": 0.3
      }
    ],
    "visRank": 13,
    "gapRank": 17
  },
  {
    "id": "BUF00",
    "name": "Highmark Stadium",
    "teams": [
      "BUF"
    ],
    "roof": "outdoors",
    "surface": "a_turf",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 192,
    "visN": 330,
    "visPct": 84.8,
    "visExp": 86.0,
    "visDiff": -1.1,
    "visZ": -0.62,
    "homeN": 360,
    "homePct": 81.9,
    "homeDiff": -4.4,
    "gap": -3.3,
    "gapZ": -1.35,
    "bands": {
      "u30": {
        "diff": 0.9,
        "n": 91
      },
      "d30": {
        "diff": -3.9,
        "n": 96
      },
      "d40": {
        "diff": 0.7,
        "n": 107
      },
      "d50": {
        "diff": -4.3,
        "n": 36
      }
    },
    "windyDiff": -4.6,
    "windyN": 91,
    "puntOE": -0.95,
    "puntN": 1723,
    "koDistOE": -1.27,
    "touchback": 50.4,
    "homeLongKickRate": 14.3,
    "homeLongKickN": 133,
    "wideOnly": 77.6,
    "missN": 49,
    "dirSplit": 2.5,
    "bySeason": [
      {
        "season": 2002,
        "n": 12,
        "diff": 8.4
      },
      {
        "season": 2003,
        "n": 15,
        "diff": 2.7
      },
      {
        "season": 2004,
        "n": 15,
        "diff": -1.5
      },
      {
        "season": 2005,
        "n": 8,
        "diff": -21.3
      },
      {
        "season": 2006,
        "n": 10,
        "diff": -2.0
      },
      {
        "season": 2007,
        "n": 12,
        "diff": -3.1
      },
      {
        "season": 2008,
        "n": 18,
        "diff": -0.6
      },
      {
        "season": 2009,
        "n": 8,
        "diff": 6.7
      },
      {
        "season": 2010,
        "n": 21,
        "diff": 3.8
      },
      {
        "season": 2011,
        "n": 11,
        "diff": 5.2
      },
      {
        "season": 2012,
        "n": 9,
        "diff": -20.2
      },
      {
        "season": 2013,
        "n": 15,
        "diff": -3.6
      },
      {
        "season": 2014,
        "n": 15,
        "diff": -0.7
      },
      {
        "season": 2015,
        "n": 14,
        "diff": -5.5
      },
      {
        "season": 2016,
        "n": 16,
        "diff": 10.2
      },
      {
        "season": 2017,
        "n": 17,
        "diff": 1.6
      },
      {
        "season": 2018,
        "n": 17,
        "diff": -4.5
      },
      {
        "season": 2019,
        "n": 12,
        "diff": -2.4
      },
      {
        "season": 2020,
        "n": 17,
        "diff": -12.5
      },
      {
        "season": 2021,
        "n": 12,
        "diff": 10.4
      },
      {
        "season": 2022,
        "n": 17,
        "diff": -9.4
      },
      {
        "season": 2023,
        "n": 14,
        "diff": 5.8
      },
      {
        "season": 2024,
        "n": 12,
        "diff": -14.0
      },
      {
        "season": 2025,
        "n": 13,
        "diff": 10.2
      }
    ],
    "visRank": 13,
    "gapRank": 35
  },
  {
    "id": "SDG00",
    "name": "Qualcomm Stadium",
    "teams": [
      "LAC"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2016,
    "games": 122,
    "visN": 199,
    "visPct": 84.4,
    "visExp": 85.4,
    "visDiff": -1.0,
    "visZ": -0.43,
    "homeN": 229,
    "homePct": 86.5,
    "homeDiff": 0.3,
    "gap": 1.3,
    "gapZ": 0.41,
    "bands": {
      "u30": {
        "diff": -0.8,
        "n": 62
      },
      "d30": {
        "diff": -6.9,
        "n": 60
      },
      "d40": {
        "diff": 7.5,
        "n": 56
      },
      "d50": {
        "diff": -7.2,
        "n": 21
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 0.12,
    "puntN": 1064,
    "koDistOE": 0.42,
    "touchback": 45.2,
    "homeLongKickRate": 13.4,
    "homeLongKickN": 67,
    "wideOnly": 90.3,
    "missN": 31,
    "dirSplit": 4.7,
    "bySeason": [
      {
        "season": 2002,
        "n": 18,
        "diff": -3.5
      },
      {
        "season": 2003,
        "n": 7,
        "diff": 21.7
      },
      {
        "season": 2004,
        "n": 14,
        "diff": -20.9
      },
      {
        "season": 2005,
        "n": 13,
        "diff": 1.3
      },
      {
        "season": 2006,
        "n": 20,
        "diff": 9.7
      },
      {
        "season": 2007,
        "n": 11,
        "diff": -16.3
      },
      {
        "season": 2008,
        "n": 13,
        "diff": 8.6
      },
      {
        "season": 2009,
        "n": 18,
        "diff": 5.5
      },
      {
        "season": 2010,
        "n": 7,
        "diff": 20.0
      },
      {
        "season": 2011,
        "n": 14,
        "diff": -7.4
      },
      {
        "season": 2012,
        "n": 10,
        "diff": 0.4
      },
      {
        "season": 2013,
        "n": 11,
        "diff": -9.1
      },
      {
        "season": 2014,
        "n": 14,
        "diff": 8.5
      },
      {
        "season": 2015,
        "n": 14,
        "diff": -12.7
      },
      {
        "season": 2016,
        "n": 15,
        "diff": -7.9
      }
    ],
    "visRank": 15,
    "gapRank": 16
  },
  {
    "id": "PHO00",
    "name": "State Farm Stadium",
    "teams": [
      "ARI"
    ],
    "roof": "closed",
    "surface": "grass",
    "firstSeason": 2006,
    "lastSeason": 2025,
    "games": 170,
    "visN": 334,
    "visPct": 85.0,
    "visExp": 85.6,
    "visDiff": -0.6,
    "visZ": -0.34,
    "homeN": 332,
    "homePct": 83.7,
    "homeDiff": -1.4,
    "gap": -0.7,
    "gapZ": -0.29,
    "bands": {
      "u30": {
        "diff": -2.7,
        "n": 88
      },
      "d30": {
        "diff": -3.6,
        "n": 86
      },
      "d40": {
        "diff": 0.8,
        "n": 98
      },
      "d50": {
        "diff": 4.3,
        "n": 62
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 0.96,
    "puntN": 1514,
    "koDistOE": 0.61,
    "touchback": 63.3,
    "homeLongKickRate": 16.3,
    "homeLongKickN": 123,
    "wideOnly": 80.0,
    "missN": 50,
    "dirSplit": 4.1,
    "bySeason": [
      {
        "season": 2006,
        "n": 17,
        "diff": 0.4
      },
      {
        "season": 2007,
        "n": 16,
        "diff": 0.3
      },
      {
        "season": 2008,
        "n": 15,
        "diff": -10.7
      },
      {
        "season": 2009,
        "n": 13,
        "diff": -3.3
      },
      {
        "season": 2010,
        "n": 28,
        "diff": -10.8
      },
      {
        "season": 2011,
        "n": 19,
        "diff": 1.1
      },
      {
        "season": 2012,
        "n": 13,
        "diff": -4.2
      },
      {
        "season": 2013,
        "n": 14,
        "diff": -0.9
      },
      {
        "season": 2014,
        "n": 10,
        "diff": -12.6
      },
      {
        "season": 2015,
        "n": 15,
        "diff": 7.3
      },
      {
        "season": 2016,
        "n": 16,
        "diff": 3.5
      },
      {
        "season": 2017,
        "n": 14,
        "diff": 2.7
      },
      {
        "season": 2018,
        "n": 18,
        "diff": -7.7
      },
      {
        "season": 2019,
        "n": 15,
        "diff": -0.5
      },
      {
        "season": 2020,
        "n": 24,
        "diff": -1.0
      },
      {
        "season": 2021,
        "n": 17,
        "diff": 5.5
      },
      {
        "season": 2022,
        "n": 17,
        "diff": 4.1
      },
      {
        "season": 2023,
        "n": 14,
        "diff": -3.4
      },
      {
        "season": 2024,
        "n": 21,
        "diff": 6.5
      },
      {
        "season": 2025,
        "n": 18,
        "diff": 9.7
      }
    ],
    "visRank": 16,
    "gapRank": 21
  },
  {
    "id": "DET00",
    "name": "Ford Field",
    "teams": [
      "DET"
    ],
    "roof": "dome",
    "surface": "fieldturf",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 197,
    "visN": 364,
    "visPct": 83.2,
    "visExp": 83.3,
    "visDiff": -0.1,
    "visZ": -0.06,
    "homeN": 369,
    "homePct": 88.9,
    "homeDiff": 5.5,
    "gap": 5.6,
    "gapZ": 2.2,
    "bands": {
      "u30": {
        "diff": 1.1,
        "n": 93
      },
      "d30": {
        "diff": -2.7,
        "n": 87
      },
      "d40": {
        "diff": 1.5,
        "n": 112
      },
      "d50": {
        "diff": -1.0,
        "n": 72
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 0.33,
    "puntN": 1705,
    "koDistOE": 0.53,
    "touchback": 60.4,
    "homeLongKickRate": 26.3,
    "homeLongKickN": 137,
    "wideOnly": 71.2,
    "missN": 59,
    "dirSplit": 1.8,
    "bySeason": [
      {
        "season": 2002,
        "n": 12,
        "diff": 18.4
      },
      {
        "season": 2003,
        "n": 11,
        "diff": -3.7
      },
      {
        "season": 2004,
        "n": 9,
        "diff": 9.9
      },
      {
        "season": 2005,
        "n": 13,
        "diff": 5.4
      },
      {
        "season": 2006,
        "n": 16,
        "diff": 16.3
      },
      {
        "season": 2007,
        "n": 14,
        "diff": -9.8
      },
      {
        "season": 2008,
        "n": 17,
        "diff": 12.9
      },
      {
        "season": 2009,
        "n": 12,
        "diff": 8.3
      },
      {
        "season": 2010,
        "n": 12,
        "diff": 15.3
      },
      {
        "season": 2011,
        "n": 15,
        "diff": 7.0
      },
      {
        "season": 2012,
        "n": 20,
        "diff": -14.3
      },
      {
        "season": 2013,
        "n": 23,
        "diff": 6.7
      },
      {
        "season": 2014,
        "n": 15,
        "diff": 1.8
      },
      {
        "season": 2015,
        "n": 16,
        "diff": -3.1
      },
      {
        "season": 2016,
        "n": 13,
        "diff": 2.1
      },
      {
        "season": 2017,
        "n": 14,
        "diff": -2.3
      },
      {
        "season": 2018,
        "n": 15,
        "diff": -20.7
      },
      {
        "season": 2019,
        "n": 16,
        "diff": -21.8
      },
      {
        "season": 2020,
        "n": 11,
        "diff": -14.0
      },
      {
        "season": 2021,
        "n": 23,
        "diff": 2.4
      },
      {
        "season": 2022,
        "n": 13,
        "diff": 2.3
      },
      {
        "season": 2023,
        "n": 21,
        "diff": -9.8
      },
      {
        "season": 2024,
        "n": 17,
        "diff": -6.1
      },
      {
        "season": 2025,
        "n": 16,
        "diff": 5.7
      }
    ],
    "visRank": 17,
    "gapRank": 2
  },
  {
    "id": "IND00",
    "name": "Lucas Oil Stadium",
    "teams": [
      "IND"
    ],
    "roof": "closed",
    "surface": "fieldturf",
    "firstSeason": 2008,
    "lastSeason": 2025,
    "games": 152,
    "visN": 286,
    "visPct": 84.6,
    "visExp": 84.7,
    "visDiff": -0.1,
    "visZ": -0.03,
    "homeN": 306,
    "homePct": 88.9,
    "homeDiff": 3.2,
    "gap": 3.3,
    "gapZ": 1.19,
    "bands": {
      "u30": {
        "diff": 0.7,
        "n": 71
      },
      "d30": {
        "diff": 0.5,
        "n": 71
      },
      "d40": {
        "diff": 0.5,
        "n": 88
      },
      "d50": {
        "diff": -2.5,
        "n": 56
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 0.72,
    "puntN": 1262,
    "koDistOE": 0.56,
    "touchback": 63.6,
    "homeLongKickRate": 28.6,
    "homeLongKickN": 98,
    "wideOnly": 72.1,
    "missN": 43,
    "dirSplit": -0.2,
    "bySeason": [
      {
        "season": 2008,
        "n": 15,
        "diff": 3.9
      },
      {
        "season": 2009,
        "n": 17,
        "diff": -5.9
      },
      {
        "season": 2010,
        "n": 20,
        "diff": 4.6
      },
      {
        "season": 2011,
        "n": 18,
        "diff": 2.5
      },
      {
        "season": 2012,
        "n": 19,
        "diff": -4.5
      },
      {
        "season": 2013,
        "n": 15,
        "diff": 7.8
      },
      {
        "season": 2014,
        "n": 12,
        "diff": 4.5
      },
      {
        "season": 2015,
        "n": 18,
        "diff": -13.1
      },
      {
        "season": 2016,
        "n": 22,
        "diff": -5.3
      },
      {
        "season": 2017,
        "n": 18,
        "diff": -4.1
      },
      {
        "season": 2018,
        "n": 14,
        "diff": 1.5
      },
      {
        "season": 2019,
        "n": 14,
        "diff": 7.7
      },
      {
        "season": 2020,
        "n": 9,
        "diff": 4.3
      },
      {
        "season": 2021,
        "n": 13,
        "diff": 5.7
      },
      {
        "season": 2022,
        "n": 11,
        "diff": -2.1
      },
      {
        "season": 2023,
        "n": 19,
        "diff": 6.0
      },
      {
        "season": 2024,
        "n": 16,
        "diff": 3.1
      },
      {
        "season": 2025,
        "n": 16,
        "diff": -9.8
      }
    ],
    "visRank": 17,
    "gapRank": 8
  },
  {
    "id": "KAN00",
    "name": "GEHA Field at Arrowhead Stadium",
    "teams": [
      "KC"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 205,
    "visN": 378,
    "visPct": 84.7,
    "visExp": 84.7,
    "visDiff": -0.1,
    "visZ": -0.03,
    "homeN": 411,
    "homePct": 84.7,
    "homeDiff": -1.5,
    "gap": -1.4,
    "gapZ": -0.62,
    "bands": {
      "u30": {
        "diff": -0.8,
        "n": 93
      },
      "d30": {
        "diff": 2.6,
        "n": 124
      },
      "d40": {
        "diff": 6.4,
        "n": 101
      },
      "d50": {
        "diff": -15.3,
        "n": 60
      }
    },
    "windyDiff": -2.2,
    "windyN": 62,
    "puntOE": 0.3,
    "puntN": 1713,
    "koDistOE": -0.24,
    "touchback": 52.4,
    "homeLongKickRate": 16.7,
    "homeLongKickN": 126,
    "wideOnly": 77.2,
    "missN": 57,
    "dirSplit": -1.4,
    "bySeason": [
      {
        "season": 2002,
        "n": 17,
        "diff": 1.9
      },
      {
        "season": 2003,
        "n": 15,
        "diff": 4.4
      },
      {
        "season": 2004,
        "n": 15,
        "diff": 1.3
      },
      {
        "season": 2005,
        "n": 10,
        "diff": 19.1
      },
      {
        "season": 2006,
        "n": 13,
        "diff": 1.3
      },
      {
        "season": 2007,
        "n": 20,
        "diff": 3.1
      },
      {
        "season": 2008,
        "n": 22,
        "diff": 8.7
      },
      {
        "season": 2009,
        "n": 23,
        "diff": -3.3
      },
      {
        "season": 2010,
        "n": 13,
        "diff": 6.0
      },
      {
        "season": 2011,
        "n": 18,
        "diff": -4.9
      },
      {
        "season": 2012,
        "n": 20,
        "diff": -4.1
      },
      {
        "season": 2013,
        "n": 15,
        "diff": -5.5
      },
      {
        "season": 2014,
        "n": 16,
        "diff": -1.8
      },
      {
        "season": 2015,
        "n": 11,
        "diff": 1.3
      },
      {
        "season": 2016,
        "n": 20,
        "diff": 4.4
      },
      {
        "season": 2017,
        "n": 16,
        "diff": -4.8
      },
      {
        "season": 2018,
        "n": 9,
        "diff": -8.1
      },
      {
        "season": 2019,
        "n": 15,
        "diff": -7.7
      },
      {
        "season": 2020,
        "n": 18,
        "diff": -3.1
      },
      {
        "season": 2021,
        "n": 15,
        "diff": -5.3
      },
      {
        "season": 2022,
        "n": 16,
        "diff": 0.7
      },
      {
        "season": 2023,
        "n": 7,
        "diff": 8.5
      },
      {
        "season": 2024,
        "n": 20,
        "diff": -11.0
      },
      {
        "season": 2025,
        "n": 14,
        "diff": 9.2
      }
    ],
    "visRank": 17,
    "gapRank": 27
  },
  {
    "id": "CIN00",
    "name": "Paycor Stadium",
    "teams": [
      "CIN"
    ],
    "roof": "outdoors",
    "surface": "fieldturf",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 196,
    "visN": 380,
    "visPct": 87.1,
    "visExp": 87.2,
    "visDiff": -0.0,
    "visZ": -0.03,
    "homeN": 378,
    "homePct": 85.2,
    "homeDiff": -0.9,
    "gap": -0.8,
    "gapZ": -0.36,
    "bands": {
      "u30": {
        "diff": -0.2,
        "n": 130
      },
      "d30": {
        "diff": -1.3,
        "n": 96
      },
      "d40": {
        "diff": 2.3,
        "n": 110
      },
      "d50": {
        "diff": -2.6,
        "n": 44
      }
    },
    "windyDiff": -6.9,
    "windyN": 36,
    "puntOE": -0.68,
    "puntN": 1711,
    "koDistOE": 0.04,
    "touchback": 50.2,
    "homeLongKickRate": 14.8,
    "homeLongKickN": 128,
    "wideOnly": 73.5,
    "missN": 49,
    "dirSplit": 1.1,
    "bySeason": [
      {
        "season": 2002,
        "n": 16,
        "diff": -15.3
      },
      {
        "season": 2003,
        "n": 16,
        "diff": 3.3
      },
      {
        "season": 2004,
        "n": 18,
        "diff": 7.9
      },
      {
        "season": 2005,
        "n": 12,
        "diff": -4.8
      },
      {
        "season": 2006,
        "n": 10,
        "diff": -13.4
      },
      {
        "season": 2007,
        "n": 13,
        "diff": -0.5
      },
      {
        "season": 2008,
        "n": 12,
        "diff": 7.3
      },
      {
        "season": 2009,
        "n": 10,
        "diff": -10.8
      },
      {
        "season": 2010,
        "n": 16,
        "diff": 2.1
      },
      {
        "season": 2011,
        "n": 14,
        "diff": 4.5
      },
      {
        "season": 2012,
        "n": 15,
        "diff": 5.5
      },
      {
        "season": 2013,
        "n": 17,
        "diff": 3.0
      },
      {
        "season": 2014,
        "n": 16,
        "diff": -15.9
      },
      {
        "season": 2015,
        "n": 24,
        "diff": 7.3
      },
      {
        "season": 2016,
        "n": 13,
        "diff": 7.0
      },
      {
        "season": 2017,
        "n": 21,
        "diff": -2.5
      },
      {
        "season": 2018,
        "n": 14,
        "diff": 5.9
      },
      {
        "season": 2019,
        "n": 20,
        "diff": 0.3
      },
      {
        "season": 2020,
        "n": 20,
        "diff": -2.1
      },
      {
        "season": 2021,
        "n": 22,
        "diff": -11.0
      },
      {
        "season": 2022,
        "n": 15,
        "diff": -1.7
      },
      {
        "season": 2023,
        "n": 17,
        "diff": -0.3
      },
      {
        "season": 2024,
        "n": 14,
        "diff": 12.5
      },
      {
        "season": 2025,
        "n": 15,
        "diff": 7.7
      }
    ],
    "visRank": 20,
    "gapRank": 22
  },
  {
    "id": "NYC01",
    "name": "MetLife Stadium",
    "teams": [
      "NYG",
      "NYJ"
    ],
    "roof": "outdoors",
    "surface": "fieldturf",
    "firstSeason": 2010,
    "lastSeason": 2025,
    "games": 261,
    "visN": 550,
    "visPct": 86.5,
    "visExp": 86.5,
    "visDiff": 0.0,
    "visZ": 0.01,
    "homeN": 473,
    "homePct": 85.6,
    "homeDiff": -1.9,
    "gap": -1.9,
    "gapZ": -0.95,
    "bands": {
      "u30": {
        "diff": -2.2,
        "n": 130
      },
      "d30": {
        "diff": 0.5,
        "n": 166
      },
      "d40": {
        "diff": 2.5,
        "n": 167
      },
      "d50": {
        "diff": -2.4,
        "n": 87
      }
    },
    "windyDiff": -0.6,
    "windyN": 64,
    "puntOE": -0.26,
    "puntN": 2473,
    "koDistOE": -0.38,
    "touchback": 47.3,
    "homeLongKickRate": 18.8,
    "homeLongKickN": 176,
    "wideOnly": 84.9,
    "missN": 73,
    "dirSplit": 2.2,
    "bySeason": [
      {
        "season": 2010,
        "n": 26,
        "diff": -4.4
      },
      {
        "season": 2011,
        "n": 25,
        "diff": 7.1
      },
      {
        "season": 2012,
        "n": 32,
        "diff": -2.1
      },
      {
        "season": 2013,
        "n": 43,
        "diff": 2.8
      },
      {
        "season": 2014,
        "n": 35,
        "diff": 3.9
      },
      {
        "season": 2015,
        "n": 25,
        "diff": 11.9
      },
      {
        "season": 2016,
        "n": 39,
        "diff": 3.6
      },
      {
        "season": 2017,
        "n": 32,
        "diff": -9.7
      },
      {
        "season": 2018,
        "n": 36,
        "diff": -1.7
      },
      {
        "season": 2019,
        "n": 37,
        "diff": 5.8
      },
      {
        "season": 2020,
        "n": 43,
        "diff": 6.7
      },
      {
        "season": 2021,
        "n": 39,
        "diff": 0.4
      },
      {
        "season": 2022,
        "n": 47,
        "diff": -8.1
      },
      {
        "season": 2023,
        "n": 29,
        "diff": -8.4
      },
      {
        "season": 2024,
        "n": 29,
        "diff": -8.7
      },
      {
        "season": 2025,
        "n": 33,
        "diff": 1.3
      }
    ],
    "visRank": 20,
    "gapRank": 30
  },
  {
    "id": "NAS00",
    "name": "Nissan Stadium",
    "teams": [
      "TEN"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 196,
    "visN": 373,
    "visPct": 86.6,
    "visExp": 86.6,
    "visDiff": 0.0,
    "visZ": 0.02,
    "homeN": 357,
    "homePct": 86.3,
    "homeDiff": 1.9,
    "gap": 1.9,
    "gapZ": 0.78,
    "bands": {
      "u30": {
        "diff": 0.4,
        "n": 122
      },
      "d30": {
        "diff": -5.4,
        "n": 100
      },
      "d40": {
        "diff": 5.4,
        "n": 94
      },
      "d50": {
        "diff": -0.2,
        "n": 57
      }
    },
    "windyDiff": null,
    "windyN": 20,
    "puntOE": 0.73,
    "puntN": 1816,
    "koDistOE": -0.22,
    "touchback": 51.8,
    "homeLongKickRate": 10.2,
    "homeLongKickN": 127,
    "wideOnly": 72.0,
    "missN": 50,
    "dirSplit": -0.7,
    "bySeason": [
      {
        "season": 2002,
        "n": 13,
        "diff": -15.2
      },
      {
        "season": 2003,
        "n": 15,
        "diff": 6.8
      },
      {
        "season": 2004,
        "n": 13,
        "diff": -4.2
      },
      {
        "season": 2005,
        "n": 10,
        "diff": -21.0
      },
      {
        "season": 2006,
        "n": 14,
        "diff": -24.7
      },
      {
        "season": 2007,
        "n": 17,
        "diff": -13.2
      },
      {
        "season": 2008,
        "n": 18,
        "diff": -10.9
      },
      {
        "season": 2009,
        "n": 8,
        "diff": 10.5
      },
      {
        "season": 2010,
        "n": 27,
        "diff": 0.9
      },
      {
        "season": 2011,
        "n": 11,
        "diff": 7.6
      },
      {
        "season": 2012,
        "n": 17,
        "diff": 6.8
      },
      {
        "season": 2013,
        "n": 17,
        "diff": 12.7
      },
      {
        "season": 2014,
        "n": 21,
        "diff": 6.2
      },
      {
        "season": 2015,
        "n": 8,
        "diff": -4.9
      },
      {
        "season": 2016,
        "n": 16,
        "diff": -4.9
      },
      {
        "season": 2017,
        "n": 15,
        "diff": -5.6
      },
      {
        "season": 2018,
        "n": 17,
        "diff": 6.5
      },
      {
        "season": 2019,
        "n": 13,
        "diff": 17.3
      },
      {
        "season": 2020,
        "n": 14,
        "diff": 5.8
      },
      {
        "season": 2021,
        "n": 21,
        "diff": 0.2
      },
      {
        "season": 2022,
        "n": 14,
        "diff": 8.5
      },
      {
        "season": 2023,
        "n": 20,
        "diff": 8.9
      },
      {
        "season": 2024,
        "n": 12,
        "diff": 0.7
      },
      {
        "season": 2025,
        "n": 22,
        "diff": -1.7
      }
    ],
    "visRank": 20,
    "gapRank": 15
  },
  {
    "id": "CAR00",
    "name": "Bank of America Stadium",
    "teams": [
      "CAR"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 198,
    "visN": 382,
    "visPct": 85.3,
    "visExp": 85.0,
    "visDiff": 0.3,
    "visZ": 0.18,
    "homeN": 365,
    "homePct": 88.2,
    "homeDiff": 3.4,
    "gap": 3.1,
    "gapZ": 1.26,
    "bands": {
      "u30": {
        "diff": 1.3,
        "n": 101
      },
      "d30": {
        "diff": -0.3,
        "n": 122
      },
      "d40": {
        "diff": -0.1,
        "n": 102
      },
      "d50": {
        "diff": 0.4,
        "n": 57
      }
    },
    "windyDiff": 0.3,
    "windyN": 26,
    "puntOE": 0.35,
    "puntN": 1860,
    "koDistOE": 0.07,
    "touchback": 63.0,
    "homeLongKickRate": 19.1,
    "homeLongKickN": 136,
    "wideOnly": 76.4,
    "missN": 55,
    "dirSplit": 3.3,
    "bySeason": [
      {
        "season": 2002,
        "n": 12,
        "diff": 12.2
      },
      {
        "season": 2003,
        "n": 17,
        "diff": 3.0
      },
      {
        "season": 2004,
        "n": 12,
        "diff": -25.4
      },
      {
        "season": 2005,
        "n": 12,
        "diff": 1.4
      },
      {
        "season": 2006,
        "n": 18,
        "diff": -3.0
      },
      {
        "season": 2007,
        "n": 12,
        "diff": 6.8
      },
      {
        "season": 2008,
        "n": 17,
        "diff": -2.6
      },
      {
        "season": 2009,
        "n": 14,
        "diff": -14.6
      },
      {
        "season": 2010,
        "n": 17,
        "diff": 13.7
      },
      {
        "season": 2011,
        "n": 17,
        "diff": 3.0
      },
      {
        "season": 2012,
        "n": 21,
        "diff": 8.5
      },
      {
        "season": 2013,
        "n": 18,
        "diff": 0.2
      },
      {
        "season": 2014,
        "n": 16,
        "diff": -2.9
      },
      {
        "season": 2015,
        "n": 13,
        "diff": -0.6
      },
      {
        "season": 2016,
        "n": 20,
        "diff": 1.2
      },
      {
        "season": 2017,
        "n": 17,
        "diff": -1.3
      },
      {
        "season": 2018,
        "n": 11,
        "diff": -2.9
      },
      {
        "season": 2019,
        "n": 20,
        "diff": -14.1
      },
      {
        "season": 2020,
        "n": 16,
        "diff": 4.7
      },
      {
        "season": 2021,
        "n": 18,
        "diff": -3.2
      },
      {
        "season": 2022,
        "n": 14,
        "diff": -1.5
      },
      {
        "season": 2023,
        "n": 11,
        "diff": 12.5
      },
      {
        "season": 2024,
        "n": 25,
        "diff": 9.5
      },
      {
        "season": 2025,
        "n": 14,
        "diff": -3.3
      }
    ],
    "visRank": 23,
    "gapRank": 10
  },
  {
    "id": "BAL00",
    "name": "M&T Bank Stadium",
    "teams": [
      "BAL"
    ],
    "roof": "outdoors",
    "surface": "sportturf",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 199,
    "visN": 366,
    "visPct": 85.2,
    "visExp": 84.7,
    "visDiff": 0.5,
    "visZ": 0.29,
    "homeN": 444,
    "homePct": 89.2,
    "homeDiff": 3.9,
    "gap": 3.4,
    "gapZ": 1.44,
    "bands": {
      "u30": {
        "diff": -0.3,
        "n": 90
      },
      "d30": {
        "diff": 6.0,
        "n": 103
      },
      "d40": {
        "diff": -5.2,
        "n": 110
      },
      "d50": {
        "diff": 2.4,
        "n": 63
      }
    },
    "windyDiff": null,
    "windyN": 22,
    "puntOE": -0.1,
    "puntN": 1877,
    "koDistOE": -0.44,
    "touchback": 55.3,
    "homeLongKickRate": 21.3,
    "homeLongKickN": 136,
    "wideOnly": 81.1,
    "missN": 53,
    "dirSplit": -8.0,
    "bySeason": [
      {
        "season": 2002,
        "n": 18,
        "diff": 1.0
      },
      {
        "season": 2003,
        "n": 15,
        "diff": 22.1
      },
      {
        "season": 2004,
        "n": 13,
        "diff": -10.0
      },
      {
        "season": 2005,
        "n": 15,
        "diff": 6.5
      },
      {
        "season": 2006,
        "n": 18,
        "diff": 9.5
      },
      {
        "season": 2007,
        "n": 23,
        "diff": -2.7
      },
      {
        "season": 2008,
        "n": 9,
        "diff": -0.1
      },
      {
        "season": 2009,
        "n": 7,
        "diff": 2.9
      },
      {
        "season": 2010,
        "n": 11,
        "diff": -3.6
      },
      {
        "season": 2011,
        "n": 10,
        "diff": 6.2
      },
      {
        "season": 2012,
        "n": 24,
        "diff": 4.3
      },
      {
        "season": 2013,
        "n": 17,
        "diff": -0.1
      },
      {
        "season": 2014,
        "n": 17,
        "diff": 5.7
      },
      {
        "season": 2015,
        "n": 13,
        "diff": 8.1
      },
      {
        "season": 2016,
        "n": 10,
        "diff": -16.5
      },
      {
        "season": 2017,
        "n": 16,
        "diff": -10.1
      },
      {
        "season": 2018,
        "n": 15,
        "diff": -5.6
      },
      {
        "season": 2019,
        "n": 11,
        "diff": -3.8
      },
      {
        "season": 2020,
        "n": 12,
        "diff": -28.4
      },
      {
        "season": 2021,
        "n": 13,
        "diff": -8.5
      },
      {
        "season": 2022,
        "n": 18,
        "diff": 2.3
      },
      {
        "season": 2023,
        "n": 25,
        "diff": 5.6
      },
      {
        "season": 2024,
        "n": 13,
        "diff": 9.3
      },
      {
        "season": 2025,
        "n": 23,
        "diff": 0.7
      }
    ],
    "visRank": 24,
    "gapRank": 7
  },
  {
    "id": "PHI00",
    "name": "Lincoln Financial Field",
    "teams": [
      "PHI"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2003,
    "lastSeason": 2025,
    "games": 200,
    "visN": 319,
    "visPct": 86.5,
    "visExp": 85.3,
    "visDiff": 1.2,
    "visZ": 0.64,
    "homeN": 395,
    "homePct": 86.1,
    "homeDiff": -0.0,
    "gap": -1.2,
    "gapZ": -0.49,
    "bands": {
      "u30": {
        "diff": -1.3,
        "n": 87
      },
      "d30": {
        "diff": -0.6,
        "n": 91
      },
      "d40": {
        "diff": 3.3,
        "n": 95
      },
      "d50": {
        "diff": 4.9,
        "n": 46
      }
    },
    "windyDiff": 1.2,
    "windyN": 56,
    "puntOE": -1.14,
    "puntN": 1830,
    "koDistOE": -0.26,
    "touchback": 50.3,
    "homeLongKickRate": 12.5,
    "homeLongKickN": 144,
    "wideOnly": 72.1,
    "missN": 43,
    "dirSplit": 8.6,
    "bySeason": [
      {
        "season": 2003,
        "n": 14,
        "diff": 9.4
      },
      {
        "season": 2004,
        "n": 14,
        "diff": -6.3
      },
      {
        "season": 2005,
        "n": 12,
        "diff": -14.9
      },
      {
        "season": 2006,
        "n": 15,
        "diff": 6.3
      },
      {
        "season": 2007,
        "n": 17,
        "diff": -12.7
      },
      {
        "season": 2008,
        "n": 12,
        "diff": 15.8
      },
      {
        "season": 2009,
        "n": 11,
        "diff": 5.7
      },
      {
        "season": 2010,
        "n": 10,
        "diff": 0.0
      },
      {
        "season": 2011,
        "n": 12,
        "diff": -20.0
      },
      {
        "season": 2012,
        "n": 18,
        "diff": 9.4
      },
      {
        "season": 2013,
        "n": 20,
        "diff": 7.3
      },
      {
        "season": 2014,
        "n": 8,
        "diff": -6.3
      },
      {
        "season": 2015,
        "n": 11,
        "diff": 5.5
      },
      {
        "season": 2016,
        "n": 16,
        "diff": 0.5
      },
      {
        "season": 2017,
        "n": 12,
        "diff": -9.3
      },
      {
        "season": 2018,
        "n": 19,
        "diff": -4.3
      },
      {
        "season": 2019,
        "n": 14,
        "diff": 9.7
      },
      {
        "season": 2020,
        "n": 18,
        "diff": 3.7
      },
      {
        "season": 2021,
        "n": 7,
        "diff": 12.2
      },
      {
        "season": 2022,
        "n": 14,
        "diff": 6.9
      },
      {
        "season": 2023,
        "n": 9,
        "diff": 2.7
      },
      {
        "season": 2024,
        "n": 21,
        "diff": -1.1
      },
      {
        "season": 2025,
        "n": 15,
        "diff": 6.5
      }
    ],
    "visRank": 25,
    "gapRank": 25
  },
  {
    "id": "JAX00",
    "name": "EverBank Stadium",
    "teams": [
      "JAX"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 186,
    "visN": 350,
    "visPct": 86.3,
    "visExp": 84.8,
    "visDiff": 1.5,
    "visZ": 0.85,
    "homeN": 359,
    "homePct": 84.1,
    "homeDiff": 0.1,
    "gap": -1.4,
    "gapZ": -0.54,
    "bands": {
      "u30": {
        "diff": 1.0,
        "n": 86
      },
      "d30": {
        "diff": 1.2,
        "n": 99
      },
      "d40": {
        "diff": 4.4,
        "n": 114
      },
      "d50": {
        "diff": -3.5,
        "n": 51
      }
    },
    "windyDiff": 5.2,
    "windyN": 42,
    "puntOE": 0.4,
    "puntN": 1726,
    "koDistOE": -0.12,
    "touchback": 60.9,
    "homeLongKickRate": 18.9,
    "homeLongKickN": 132,
    "wideOnly": 77.8,
    "missN": 45,
    "dirSplit": 3.0,
    "bySeason": [
      {
        "season": 2002,
        "n": 14,
        "diff": -2.4
      },
      {
        "season": 2003,
        "n": 12,
        "diff": 10.3
      },
      {
        "season": 2004,
        "n": 13,
        "diff": -12.4
      },
      {
        "season": 2005,
        "n": 13,
        "diff": 11.9
      },
      {
        "season": 2006,
        "n": 10,
        "diff": -21.2
      },
      {
        "season": 2007,
        "n": 13,
        "diff": -4.7
      },
      {
        "season": 2008,
        "n": 18,
        "diff": 4.6
      },
      {
        "season": 2009,
        "n": 13,
        "diff": -5.0
      },
      {
        "season": 2010,
        "n": 12,
        "diff": 1.8
      },
      {
        "season": 2011,
        "n": 13,
        "diff": -6.4
      },
      {
        "season": 2012,
        "n": 19,
        "diff": 1.0
      },
      {
        "season": 2013,
        "n": 13,
        "diff": 3.5
      },
      {
        "season": 2014,
        "n": 14,
        "diff": 5.1
      },
      {
        "season": 2015,
        "n": 17,
        "diff": -2.8
      },
      {
        "season": 2016,
        "n": 20,
        "diff": 6.0
      },
      {
        "season": 2017,
        "n": 10,
        "diff": 2.3
      },
      {
        "season": 2018,
        "n": 14,
        "diff": 0.5
      },
      {
        "season": 2019,
        "n": 11,
        "diff": 12.4
      },
      {
        "season": 2020,
        "n": 17,
        "diff": -3.3
      },
      {
        "season": 2021,
        "n": 16,
        "diff": 10.8
      },
      {
        "season": 2022,
        "n": 21,
        "diff": 5.1
      },
      {
        "season": 2023,
        "n": 14,
        "diff": 5.6
      },
      {
        "season": 2024,
        "n": 19,
        "diff": 5.0
      },
      {
        "season": 2025,
        "n": 14,
        "diff": -1.0
      }
    ],
    "visRank": 26,
    "gapRank": 27
  },
  {
    "id": "NOR00",
    "name": "Caesars Superdome",
    "teams": [
      "NO"
    ],
    "roof": "dome",
    "surface": "sportturf",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 192,
    "visN": 368,
    "visPct": 86.4,
    "visExp": 84.8,
    "visDiff": 1.6,
    "visZ": 0.93,
    "homeN": 356,
    "homePct": 83.1,
    "homeDiff": -2.6,
    "gap": -4.2,
    "gapZ": -1.71,
    "bands": {
      "u30": {
        "diff": -3.0,
        "n": 97
      },
      "d30": {
        "diff": 5.4,
        "n": 108
      },
      "d40": {
        "diff": 6.3,
        "n": 93
      },
      "d50": {
        "diff": -4.1,
        "n": 70
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": -0.31,
    "puntN": 1534,
    "koDistOE": 0.68,
    "touchback": 64.6,
    "homeLongKickRate": 21.7,
    "homeLongKickN": 106,
    "wideOnly": 72.0,
    "missN": 50,
    "dirSplit": -8.0,
    "bySeason": [
      {
        "season": 2002,
        "n": 12,
        "diff": 14.1
      },
      {
        "season": 2003,
        "n": 12,
        "diff": -0.7
      },
      {
        "season": 2004,
        "n": 18,
        "diff": 9.9
      },
      {
        "season": 2006,
        "n": 9,
        "diff": 8.3
      },
      {
        "season": 2007,
        "n": 18,
        "diff": -2.3
      },
      {
        "season": 2008,
        "n": 17,
        "diff": 0.2
      },
      {
        "season": 2009,
        "n": 18,
        "diff": -8.4
      },
      {
        "season": 2010,
        "n": 18,
        "diff": 5.7
      },
      {
        "season": 2011,
        "n": 17,
        "diff": 5.0
      },
      {
        "season": 2012,
        "n": 24,
        "diff": -0.8
      },
      {
        "season": 2013,
        "n": 11,
        "diff": -3.7
      },
      {
        "season": 2014,
        "n": 18,
        "diff": 14.2
      },
      {
        "season": 2015,
        "n": 11,
        "diff": -12.7
      },
      {
        "season": 2016,
        "n": 16,
        "diff": 4.6
      },
      {
        "season": 2017,
        "n": 20,
        "diff": -5.7
      },
      {
        "season": 2018,
        "n": 21,
        "diff": -1.2
      },
      {
        "season": 2019,
        "n": 16,
        "diff": 8.2
      },
      {
        "season": 2020,
        "n": 17,
        "diff": 5.9
      },
      {
        "season": 2021,
        "n": 13,
        "diff": -8.9
      },
      {
        "season": 2022,
        "n": 11,
        "diff": 16.0
      },
      {
        "season": 2023,
        "n": 18,
        "diff": -0.5
      },
      {
        "season": 2024,
        "n": 19,
        "diff": -16.2
      },
      {
        "season": 2025,
        "n": 14,
        "diff": 15.5
      }
    ],
    "visRank": 27,
    "gapRank": 36
  },
  {
    "id": "ATL00",
    "name": "Georgia Dome",
    "teams": [
      "ATL"
    ],
    "roof": "dome",
    "surface": "fieldturf",
    "firstSeason": 2002,
    "lastSeason": 2016,
    "games": 123,
    "visN": 199,
    "visPct": 85.4,
    "visExp": 83.4,
    "visDiff": 2.0,
    "visZ": 0.84,
    "homeN": 243,
    "homePct": 86.4,
    "homeDiff": 1.0,
    "gap": -1.0,
    "gapZ": -0.31,
    "bands": {
      "u30": {
        "diff": 0.2,
        "n": 55
      },
      "d30": {
        "diff": 1.8,
        "n": 54
      },
      "d40": {
        "diff": 5.3,
        "n": 58
      },
      "d50": {
        "diff": -0.3,
        "n": 32
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 0.65,
    "puntN": 1043,
    "koDistOE": 0.73,
    "touchback": 63.3,
    "homeLongKickRate": 13.7,
    "homeLongKickN": 73,
    "wideOnly": 71.4,
    "missN": 28,
    "dirSplit": 2.4,
    "bySeason": [
      {
        "season": 2002,
        "n": 8,
        "diff": -7.5
      },
      {
        "season": 2003,
        "n": 11,
        "diff": -1.0
      },
      {
        "season": 2004,
        "n": 11,
        "diff": 16.5
      },
      {
        "season": 2005,
        "n": 16,
        "diff": 11.8
      },
      {
        "season": 2006,
        "n": 11,
        "diff": -3.1
      },
      {
        "season": 2007,
        "n": 16,
        "diff": 9.7
      },
      {
        "season": 2008,
        "n": 13,
        "diff": -12.9
      },
      {
        "season": 2009,
        "n": 11,
        "diff": 3.2
      },
      {
        "season": 2010,
        "n": 10,
        "diff": -9.3
      },
      {
        "season": 2011,
        "n": 14,
        "diff": 7.0
      },
      {
        "season": 2012,
        "n": 16,
        "diff": -5.5
      },
      {
        "season": 2013,
        "n": 17,
        "diff": 12.1
      },
      {
        "season": 2014,
        "n": 14,
        "diff": 6.4
      },
      {
        "season": 2015,
        "n": 17,
        "diff": -10.2
      },
      {
        "season": 2016,
        "n": 14,
        "diff": 5.5
      }
    ],
    "visRank": 28,
    "gapRank": 23
  },
  {
    "id": "MIN01",
    "name": "U.S. Bank Stadium",
    "teams": [
      "MIN"
    ],
    "roof": "dome",
    "surface": "sportturf",
    "firstSeason": 2016,
    "lastSeason": 2025,
    "games": 83,
    "visN": 189,
    "visPct": 87.3,
    "visExp": 85.1,
    "visDiff": 2.2,
    "visZ": 0.93,
    "homeN": 165,
    "homePct": 85.5,
    "homeDiff": 0.3,
    "gap": -2.0,
    "gapZ": -0.56,
    "bands": {
      "u30": {
        "diff": 1.5,
        "n": 40
      },
      "d30": {
        "diff": 4.5,
        "n": 47
      },
      "d40": {
        "diff": -2.3,
        "n": 61
      },
      "d50": {
        "diff": 7.0,
        "n": 41
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": -0.22,
    "puntN": 636,
    "koDistOE": 0.64,
    "touchback": 66.5,
    "homeLongKickRate": 34.0,
    "homeLongKickN": 53,
    "wideOnly": null,
    "missN": 23,
    "dirSplit": 1.3,
    "bySeason": [
      {
        "season": 2016,
        "n": 12,
        "diff": 11.6
      },
      {
        "season": 2017,
        "n": 18,
        "diff": 7.3
      },
      {
        "season": 2018,
        "n": 15,
        "diff": 11.8
      },
      {
        "season": 2019,
        "n": 18,
        "diff": -2.2
      },
      {
        "season": 2020,
        "n": 25,
        "diff": 4.8
      },
      {
        "season": 2021,
        "n": 19,
        "diff": -4.9
      },
      {
        "season": 2022,
        "n": 30,
        "diff": 8.8
      },
      {
        "season": 2023,
        "n": 16,
        "diff": -3.7
      },
      {
        "season": 2024,
        "n": 17,
        "diff": -7.3
      },
      {
        "season": 2025,
        "n": 19,
        "diff": -5.0
      }
    ],
    "visRank": 29,
    "gapRank": 31
  },
  {
    "id": "DAL00",
    "name": "AT&T Stadium",
    "teams": [
      "DAL"
    ],
    "roof": "closed",
    "surface": "matrixturf",
    "firstSeason": 2009,
    "lastSeason": 2025,
    "games": 143,
    "visN": 263,
    "visPct": 88.2,
    "visExp": 85.8,
    "visDiff": 2.4,
    "visZ": 1.2,
    "homeN": 310,
    "homePct": 88.1,
    "homeDiff": 4.5,
    "gap": 2.0,
    "gapZ": 0.72,
    "bands": {
      "u30": {
        "diff": -0.7,
        "n": 65
      },
      "d30": {
        "diff": -0.5,
        "n": 75
      },
      "d40": {
        "diff": 6.3,
        "n": 72
      },
      "d50": {
        "diff": 5.5,
        "n": 51
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 0.74,
    "puntN": 1087,
    "koDistOE": 0.61,
    "touchback": 68.5,
    "homeLongKickRate": 34.7,
    "homeLongKickN": 75,
    "wideOnly": 96.8,
    "missN": 31,
    "dirSplit": 3.4,
    "bySeason": [
      {
        "season": 2009,
        "n": 13,
        "diff": -13.8
      },
      {
        "season": 2010,
        "n": 15,
        "diff": 16.3
      },
      {
        "season": 2011,
        "n": 17,
        "diff": 3.5
      },
      {
        "season": 2012,
        "n": 17,
        "diff": 6.4
      },
      {
        "season": 2013,
        "n": 12,
        "diff": 5.7
      },
      {
        "season": 2014,
        "n": 12,
        "diff": -9.0
      },
      {
        "season": 2015,
        "n": 21,
        "diff": 8.6
      },
      {
        "season": 2016,
        "n": 15,
        "diff": -9.2
      },
      {
        "season": 2017,
        "n": 13,
        "diff": -6.1
      },
      {
        "season": 2018,
        "n": 13,
        "diff": -10.7
      },
      {
        "season": 2019,
        "n": 15,
        "diff": -3.1
      },
      {
        "season": 2020,
        "n": 18,
        "diff": 15.4
      },
      {
        "season": 2021,
        "n": 21,
        "diff": 4.0
      },
      {
        "season": 2022,
        "n": 21,
        "diff": 11.6
      },
      {
        "season": 2023,
        "n": 12,
        "diff": -3.7
      },
      {
        "season": 2024,
        "n": 16,
        "diff": 5.1
      },
      {
        "season": 2025,
        "n": 12,
        "diff": 2.5
      }
    ],
    "visRank": 30,
    "gapRank": 14
  },
  {
    "id": "MIN00",
    "name": "Mall of America Field",
    "teams": [
      "MIN"
    ],
    "roof": "dome",
    "surface": "fieldturf",
    "firstSeason": 2002,
    "lastSeason": 2013,
    "games": 92,
    "visN": 170,
    "visPct": 84.7,
    "visExp": 82.0,
    "visDiff": 2.7,
    "visZ": 0.99,
    "homeN": 167,
    "homePct": 90.4,
    "homeDiff": 6.4,
    "gap": 3.7,
    "gapZ": 1.0,
    "bands": {
      "u30": {
        "diff": 2.5,
        "n": 50
      },
      "d30": {
        "diff": -0.6,
        "n": 36
      },
      "d40": {
        "diff": -0.0,
        "n": 59
      },
      "d50": {
        "diff": 14.1,
        "n": 25
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 0.45,
    "puntN": 910,
    "koDistOE": -0.54,
    "touchback": 42.0,
    "homeLongKickRate": 14.1,
    "homeLongKickN": 64,
    "wideOnly": 92.0,
    "missN": 25,
    "dirSplit": 1.9,
    "bySeason": [
      {
        "season": 2002,
        "n": 10,
        "diff": -2.5
      },
      {
        "season": 2003,
        "n": 13,
        "diff": 1.1
      },
      {
        "season": 2004,
        "n": 17,
        "diff": 3.3
      },
      {
        "season": 2005,
        "n": 15,
        "diff": -0.6
      },
      {
        "season": 2006,
        "n": 20,
        "diff": 11.6
      },
      {
        "season": 2007,
        "n": 19,
        "diff": 8.2
      },
      {
        "season": 2008,
        "n": 17,
        "diff": 0.3
      },
      {
        "season": 2009,
        "n": 12,
        "diff": -14.4
      },
      {
        "season": 2011,
        "n": 16,
        "diff": 10.0
      },
      {
        "season": 2012,
        "n": 12,
        "diff": 4.1
      },
      {
        "season": 2013,
        "n": 15,
        "diff": 2.1
      }
    ],
    "visRank": 31,
    "gapRank": 6
  },
  {
    "id": "HOU00",
    "name": "NRG Stadium",
    "teams": [
      "HOU"
    ],
    "roof": "closed",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 198,
    "visN": 371,
    "visPct": 86.0,
    "visExp": 83.2,
    "visDiff": 2.8,
    "visZ": 1.54,
    "homeN": 402,
    "homePct": 85.1,
    "homeDiff": 0.1,
    "gap": -2.7,
    "gapZ": -1.11,
    "bands": {
      "u30": {
        "diff": -0.3,
        "n": 71
      },
      "d30": {
        "diff": -1.2,
        "n": 108
      },
      "d40": {
        "diff": 2.4,
        "n": 122
      },
      "d50": {
        "diff": 12.8,
        "n": 70
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 0.58,
    "puntN": 1888,
    "koDistOE": 0.34,
    "touchback": 57.6,
    "homeLongKickRate": 21.6,
    "homeLongKickN": 148,
    "wideOnly": 86.3,
    "missN": 51,
    "dirSplit": 2.1,
    "bySeason": [
      {
        "season": 2002,
        "n": 16,
        "diff": -10.7
      },
      {
        "season": 2003,
        "n": 17,
        "diff": 4.7
      },
      {
        "season": 2004,
        "n": 19,
        "diff": 5.4
      },
      {
        "season": 2005,
        "n": 16,
        "diff": 7.2
      },
      {
        "season": 2006,
        "n": 12,
        "diff": 11.3
      },
      {
        "season": 2007,
        "n": 20,
        "diff": 9.4
      },
      {
        "season": 2008,
        "n": 15,
        "diff": 0.4
      },
      {
        "season": 2009,
        "n": 10,
        "diff": 7.8
      },
      {
        "season": 2010,
        "n": 8,
        "diff": 6.2
      },
      {
        "season": 2011,
        "n": 14,
        "diff": 5.4
      },
      {
        "season": 2012,
        "n": 16,
        "diff": 9.8
      },
      {
        "season": 2013,
        "n": 17,
        "diff": -0.1
      },
      {
        "season": 2014,
        "n": 8,
        "diff": 3.3
      },
      {
        "season": 2015,
        "n": 21,
        "diff": -0.2
      },
      {
        "season": 2016,
        "n": 19,
        "diff": 0.1
      },
      {
        "season": 2017,
        "n": 18,
        "diff": 7.2
      },
      {
        "season": 2018,
        "n": 13,
        "diff": 15.0
      },
      {
        "season": 2019,
        "n": 14,
        "diff": 16.5
      },
      {
        "season": 2020,
        "n": 17,
        "diff": -9.3
      },
      {
        "season": 2021,
        "n": 18,
        "diff": -10.3
      },
      {
        "season": 2022,
        "n": 16,
        "diff": -13.5
      },
      {
        "season": 2023,
        "n": 17,
        "diff": 0.3
      },
      {
        "season": 2024,
        "n": 18,
        "diff": 21.9
      },
      {
        "season": 2025,
        "n": 12,
        "diff": -15.6
      }
    ],
    "visRank": 32,
    "gapRank": 34
  },
  {
    "id": "STL00",
    "name": "Edward Jones Dome",
    "teams": [
      "LA"
    ],
    "roof": "dome",
    "surface": "astroplay",
    "firstSeason": 2002,
    "lastSeason": 2015,
    "games": 111,
    "visN": 221,
    "visPct": 84.6,
    "visExp": 81.6,
    "visDiff": 3.0,
    "visZ": 1.25,
    "homeN": 220,
    "homePct": 85.9,
    "homeDiff": 5.8,
    "gap": 2.8,
    "gapZ": 0.81,
    "bands": {
      "u30": {
        "diff": 0.6,
        "n": 52
      },
      "d30": {
        "diff": 2.7,
        "n": 66
      },
      "d40": {
        "diff": 3.9,
        "n": 66
      },
      "d50": {
        "diff": 5.2,
        "n": 37
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": 1.32,
    "puntN": 1081,
    "koDistOE": 1.18,
    "touchback": 53.5,
    "homeLongKickRate": 34.9,
    "homeLongKickN": 83,
    "wideOnly": 87.9,
    "missN": 33,
    "dirSplit": -2.9,
    "bySeason": [
      {
        "season": 2002,
        "n": 16,
        "diff": 9.2
      },
      {
        "season": 2003,
        "n": 15,
        "diff": 3.2
      },
      {
        "season": 2004,
        "n": 23,
        "diff": 5.9
      },
      {
        "season": 2005,
        "n": 15,
        "diff": 1.0
      },
      {
        "season": 2006,
        "n": 14,
        "diff": -0.7
      },
      {
        "season": 2007,
        "n": 18,
        "diff": 2.8
      },
      {
        "season": 2008,
        "n": 17,
        "diff": 9.9
      },
      {
        "season": 2009,
        "n": 10,
        "diff": 6.7
      },
      {
        "season": 2010,
        "n": 15,
        "diff": 5.7
      },
      {
        "season": 2011,
        "n": 17,
        "diff": -10.7
      },
      {
        "season": 2012,
        "n": 20,
        "diff": -3.0
      },
      {
        "season": 2013,
        "n": 10,
        "diff": -18.7
      },
      {
        "season": 2014,
        "n": 14,
        "diff": 16.6
      },
      {
        "season": 2015,
        "n": 17,
        "diff": 8.9
      }
    ],
    "visRank": 33,
    "gapRank": 12
  },
  {
    "id": "DEN00",
    "name": "Empower Field at Mile High",
    "teams": [
      "DEN"
    ],
    "roof": "outdoors",
    "surface": "grass",
    "firstSeason": 2002,
    "lastSeason": 2025,
    "games": 204,
    "visN": 399,
    "visPct": 86.2,
    "visExp": 83.0,
    "visDiff": 3.2,
    "visZ": 1.87,
    "homeN": 404,
    "homePct": 85.9,
    "homeDiff": 1.9,
    "gap": -1.3,
    "gapZ": -0.55,
    "bands": {
      "u30": {
        "diff": 2.1,
        "n": 91
      },
      "d30": {
        "diff": 2.1,
        "n": 107
      },
      "d40": {
        "diff": -0.6,
        "n": 123
      },
      "d50": {
        "diff": 12.2,
        "n": 78
      }
    },
    "windyDiff": null,
    "windyN": 19,
    "puntOE": 1.94,
    "puntN": 1898,
    "koDistOE": 0.48,
    "touchback": 77.8,
    "homeLongKickRate": 31.7,
    "homeLongKickN": 139,
    "wideOnly": 92.6,
    "missN": 54,
    "dirSplit": 1.3,
    "bySeason": [
      {
        "season": 2002,
        "n": 15,
        "diff": 9.0
      },
      {
        "season": 2003,
        "n": 14,
        "diff": 15.5
      },
      {
        "season": 2004,
        "n": 12,
        "diff": -11.2
      },
      {
        "season": 2005,
        "n": 14,
        "diff": 5.4
      },
      {
        "season": 2006,
        "n": 19,
        "diff": 7.4
      },
      {
        "season": 2007,
        "n": 13,
        "diff": 3.5
      },
      {
        "season": 2008,
        "n": 18,
        "diff": 2.0
      },
      {
        "season": 2009,
        "n": 16,
        "diff": 15.3
      },
      {
        "season": 2010,
        "n": 18,
        "diff": 7.4
      },
      {
        "season": 2011,
        "n": 23,
        "diff": 6.7
      },
      {
        "season": 2012,
        "n": 13,
        "diff": 6.0
      },
      {
        "season": 2013,
        "n": 13,
        "diff": -5.0
      },
      {
        "season": 2014,
        "n": 10,
        "diff": -17.0
      },
      {
        "season": 2015,
        "n": 23,
        "diff": 0.9
      },
      {
        "season": 2016,
        "n": 17,
        "diff": 2.8
      },
      {
        "season": 2017,
        "n": 9,
        "diff": 11.5
      },
      {
        "season": 2018,
        "n": 14,
        "diff": -2.9
      },
      {
        "season": 2019,
        "n": 22,
        "diff": 3.9
      },
      {
        "season": 2020,
        "n": 17,
        "diff": 0.5
      },
      {
        "season": 2021,
        "n": 17,
        "diff": 5.1
      },
      {
        "season": 2022,
        "n": 22,
        "diff": 11.7
      },
      {
        "season": 2023,
        "n": 25,
        "diff": -3.2
      },
      {
        "season": 2024,
        "n": 13,
        "diff": -0.3
      },
      {
        "season": 2025,
        "n": 22,
        "diff": -3.6
      }
    ],
    "visRank": 34,
    "gapRank": 26
  },
  {
    "id": "LAX01",
    "name": "SoFi Stadium",
    "teams": [
      "LA",
      "LAC"
    ],
    "roof": "dome",
    "surface": "matrixturf",
    "firstSeason": 2020,
    "lastSeason": 2025,
    "games": 104,
    "visN": 207,
    "visPct": 89.9,
    "visExp": 86.4,
    "visDiff": 3.5,
    "visZ": 1.58,
    "homeN": 207,
    "homePct": 88.4,
    "homeDiff": 1.1,
    "gap": -2.4,
    "gapZ": -0.76,
    "bands": {
      "u30": {
        "diff": 1.5,
        "n": 51
      },
      "d30": {
        "diff": 4.4,
        "n": 55
      },
      "d40": {
        "diff": -0.8,
        "n": 55
      },
      "d50": {
        "diff": 9.6,
        "n": 46
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": -0.02,
    "puntN": 756,
    "koDistOE": 0.29,
    "touchback": 68.8,
    "homeLongKickRate": 23.1,
    "homeLongKickN": 65,
    "wideOnly": null,
    "missN": 21,
    "dirSplit": -7.6,
    "bySeason": [
      {
        "season": 2020,
        "n": 32,
        "diff": 5.0
      },
      {
        "season": 2021,
        "n": 33,
        "diff": 8.3
      },
      {
        "season": 2022,
        "n": 34,
        "diff": 6.2
      },
      {
        "season": 2023,
        "n": 31,
        "diff": 5.2
      },
      {
        "season": 2024,
        "n": 38,
        "diff": -4.5
      },
      {
        "season": 2025,
        "n": 39,
        "diff": 2.2
      }
    ],
    "visRank": 35,
    "gapRank": 33
  },
  {
    "id": "ATL97",
    "name": "Mercedes-Benz Stadium",
    "teams": [
      "ATL"
    ],
    "roof": "closed",
    "surface": "fieldturf",
    "firstSeason": 2017,
    "lastSeason": 2025,
    "games": 73,
    "visN": 160,
    "visPct": 91.2,
    "visExp": 85.9,
    "visDiff": 5.4,
    "visZ": 2.07,
    "homeN": 172,
    "homePct": 87.2,
    "homeDiff": 3.6,
    "gap": -1.8,
    "gapZ": -0.48,
    "bands": {
      "u30": {
        "diff": 1.7,
        "n": 30
      },
      "d30": {
        "diff": 0.2,
        "n": 46
      },
      "d40": {
        "diff": 3.1,
        "n": 56
      },
      "d50": {
        "diff": 22.6,
        "n": 28
      }
    },
    "windyDiff": null,
    "windyN": 0,
    "puntOE": -0.39,
    "puntN": 539,
    "koDistOE": 0.76,
    "touchback": 67.8,
    "homeLongKickRate": 40.0,
    "homeLongKickN": 60,
    "wideOnly": null,
    "missN": 14,
    "dirSplit": 5.0,
    "bySeason": [
      {
        "season": 2017,
        "n": 11,
        "diff": 6.0
      },
      {
        "season": 2018,
        "n": 18,
        "diff": 9.9
      },
      {
        "season": 2019,
        "n": 18,
        "diff": 12.0
      },
      {
        "season": 2020,
        "n": 16,
        "diff": -5.1
      },
      {
        "season": 2021,
        "n": 18,
        "diff": 4.7
      },
      {
        "season": 2022,
        "n": 22,
        "diff": -4.5
      },
      {
        "season": 2023,
        "n": 19,
        "diff": 6.1
      },
      {
        "season": 2024,
        "n": 21,
        "diff": 19.7
      },
      {
        "season": 2025,
        "n": 17,
        "diff": -2.0
      }
    ],
    "visRank": 36,
    "gapRank": 29
  }
];
